name: validate
on: [push]
jobs:
  unit-tests:
    runs-on: macos-latest
    strategy:
      matrix:
        destination:
          [
            'platform=iOS Simulator,name=iPhone 12 Pro',
          ]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Run Tests
        run: |-
          cd Example
          xcodebuild test -scheme SwiftAudio-Example -destination "${destination}" -enableCodeCoverage YES
        env:
          destination: ${{ matrix.destination }}
      - name: Push Repo to Cocoapods
        run: pod trunk push SwiftAudioEx.podspec --allow-warnings